#!/bin/dash
# check load

load=/proc/loadavg
maxload=200

if [ -f $load ]; then
    read load1 load5 load15 procs last < $load
    if [ ${load1%.*} -gt $maxload ]; then
        echo 'deferred due to load'
        log "00_load: deferred due to load: [$SIMTA_REMOTE_IP] $load1 $load5 $load15"
        filter_exit ${MESSAGE_TEMPFAIL}
    fi
fi
